@host = http://127.0.0.1:8080/v1/cats


### Get all cats
GET {{host}}/?fields=name&offset=0&limit=2&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzNzI2MDkyfQ.tPnA3X2Hy6tzLQoP-CR9axdaqPC7y7CxfBVv9F3FikA HTTP/1.1


### Create new cats
POST {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzNzI1NjQ2fQ.RY4ZhhHwy57KplxVU52w0eQkaFe0z2oVXDAc7W2YcC8 HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Catty - monching"
}


### Update cats
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 19,
    "name": "Blackie"
}


### Delete cats
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[21,23,12,16,17]



### Get single dog
GET {{host}}/24?fields=id HTTP/1.1


### Update sing dog
PUT {{host}}/22 HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "name": "Whitie"
}


### Delete single dog
DELETE {{host}}/22 HTTP/1.1